DCT-310
reach-sh/reach-lang pull request #1033
Opened 2022-05-23 11:38 UTC by EBEREGIT

### Error code 101

Added code sample

2022-05-25 02:38 UTC, TheChronicMonster requested changes

2022-05-25 02:38 UTC, TheChronicMonster commented on hs/t/y/Fix_Throw_No_Catch.rsh
> +      try {
If we add
```
A.publish();
commit();
```
Just before the `try` then that will remove warning RW0004 and will make a cleaner `txt` output.

2022-06-03 17:27 UTC, jeapostrophe commented
`hs-test` still fails

2022-06-10 16:59 UTC, TheChronicMonster approved these changes

2022-06-10 17:16 UTC, merged