DCT-315
reach-sh/reach-lang pull request #1065
Opened 2022-05-31 09:55 UTC by EBEREGIT

### Error Message 109

- Created a new sample 
- Added code sample to the documentation

2022-05-31 11:37 UTC, TheChronicMonster requested changes

2022-05-31 12:20 UTC, EBEREGIT commented on docs/src/rsh/errors/index.md
>  This error indicates that there are multiple `{!rsh} Participant`s or `{!rsh} ParticipantClass`es
I thought that `ParticipantClass` was not to be removed?

2022-06-03 18:04 UTC, jeapostrophe commented on docs/src/rsh/errors/index.md
>  This error indicates that there are multiple `{!rsh} Participant`s or `{!rsh} ParticipantClass`es
Correct, we need to continue mentioning all of them. Even though we don't want to encourage people to use them, we have to explain the error completely.

2022-06-06 15:33 UTC, hamirmahal requested changes

2022-06-07 12:16 UTC, EBEREGIT commented on hs/t/y/Fix_Part_DuplicatePart.txt
> +Checked 7 theorems; No failures!
I still got the same output even though I used the new script. Let's see if it passes this time around.

2022-06-08 16:32 UTC, TheChronicMonster requested changes

2022-06-08 16:32 UTC, TheChronicMonster commented on docs/src/rsh/errors/index.md
@EBEREGIT We need to add a note under the heading:

`This error will not happen after version v0.1.`

See an example at [RE0047](https://docs.reach.sh/rsh/errors/#RE0047)

2022-06-10 17:34 UTC, TheChronicMonster approved these changes

2022-06-10 17:34 UTC, merged