Dct 448
reach-sh/reach-lang pull request #1076
Opened 2022-05-31 20:42 UTC by Craig-Elre

Add the `console.log` statements back to the WFS.

2022-06-01 02:47 UTC, TheChronicMonster submitted a review, later dismissed

2022-06-04 13:23 UTC, jeapostrophe commented
By adding a new line of output, you break the test scripts. You need to modify them to add another spot where you expect output

2022-06-04 13:23 UTC, jeapostrophe requested changes
See comment

2022-06-06 20:42 UTC, jeapostrophe approved these changes

2022-06-06 20:42 UTC, merged