DCT-394
reach-sh/reach-lang pull request #1094
Opened 2022-06-03 14:33 UTC by EBEREGIT

### Frontends > Utilities > protect

Added code sample

2022-06-03 14:53 UTC, TheChronicMonster requested changes

2022-06-03 14:53 UTC, TheChronicMonster commented on docs/src/frontend/index.md
> +Line 350 `{!rsh} asserts` that `null` must return a result that is of type `T_Null`.
Line 350 `{!rsh} asserts` that `null` has Reach type `T_Null`.
Line 351 `{!rsh} asserts` that `undefined` has Reach type `T_Null`.

2022-06-03 14:55 UTC, hamirmahal commented on docs/src/frontend/index.md
> +This code tests to see if variables that are supposed to be `null` returns `null`.
```suggestion
This code tests to see if variables that are supposed to be `null` return `null`.
```

2022-06-06 11:03 UTC, TheChronicMonster requested changes

2022-06-08 21:46 UTC, TheChronicMonster approved these changes

2022-06-09 15:39 UTC, merged