potential fix
reach-sh/reach-lang pull request #1210
Opened 2022-06-28 14:44 UTC by chikeabuah

draft - testing in progress

2022-06-28 15:23 UTC, jeapostrophe commented on hs/src/Reach/Eval/Core.hs
> +              showFFloat Nothing (read ns :: Double) ""
Cute. You need some tests though and to review the CI logs

2022-06-28 15:24 UTC, jeapostrophe commented on hs/src/Reach/Eval/Core.hs
> +              showFFloat Nothing (read ns :: Double) ""
And to update the docs... it says we don't support it

And make sure you update the changelog to say that we do now too

2022-06-29 16:52 UTC, chikeabuah commented
https://reachsh.slack.com/archives/CMY3E5B3J/p1656521443829079

2022-06-29 16:52 UTC, DanBurton commented
According to this: https://app.circleci.com/pipelines/github/reach-sh/reach-lang/7926/workflows/0cb4bcbf-6e78-4635-b63c-ccb9756bfbe0/jobs/142416

There's only one failure, which is hs-test. (Look at the "echo $RECORD_MESSAGE" step to see what it sent to slack)

And according to the link it provides: https://app.circleci.com/pipelines/github/reach-sh/reach-lang/7926/workflows/0cb4bcbf-6e78-4635-b63c-ccb9756bfbe0/jobs/142405

that failure is:

```
Test output was different from '/build/t/y/./scientific_notation.txt'. Output of ["diff","-u","/build/t/y/./scientific_notation.txt","/tmp/scientific_notation222-52.actual"]:
```

The diff looks trivial. It will pass if you just update the `scientific_notation.txt` file.

2022-06-29 16:54 UTC, chikeabuah commented
thank you @DanBurton

2022-06-30 02:47 UTC, jeapostrophe requested changes

2022-06-30 02:47 UTC, jeapostrophe commented on examples/new-contract1/build/child.main.mjs
>  /* eslint-disable */
You should run `./scripts/restore-build.sh` when you accidentally change these files in meaningless ways

2022-06-30 02:47 UTC, jeapostrophe commented on hs/t/n/ne1.rsh
> -'reach 0.1';
Don't delete it... move it to hs/t/y

2022-06-30 02:47 UTC, jeapostrophe commented on hs/t/y/scientific_notation.rsh
> +        const x = 10e+2;
You should add more examples of the things you expect to allow. Maybe include the exact example for ne1. Also, when you write new Reach examples, you should use the modern non-ternary style

2022-06-30 15:47 UTC, chikeabuah commented
> You should remove the build file changes, make it work with JS syntax that we can conceivably support, and add more tests, including that the values are parsed correctly.

i reverted the build changes 

i don't know what you mean by "JS syntax that we can conceivably support"

there are already tests that parse the values correctly. what other tests would you like to see?

2022-06-30 18:14 UTC, chikeabuah commented
@DanBurton any input on what Jay means above?

2022-07-01 15:57 UTC, DanBurton commented
re: "conceivably support": we could conceivably support any UInt literal that evaluates to a whole number.

Yes:

```
> 1.e2
100
> 1.1e2
110
```

No:

```
> 1.1e0
1.1
> 1e-1 // this is currently allowed but is bad
0.1
```

2022-07-01 16:16 UTC, jeapostrophe commented
We can support those examples Dan, because we already turn 0.1 into a fixed point number

2022-07-01 17:32 UTC, DanBurton commented
To amend my earlier suggestion in light of what Jay said about fixed point numbers, I think we should parse any valid scientific notation expression:

* as a fixed point number if it has a decimal
* else as a fixed point number if it has no decimal but has a negative exponent
* else as an Int if it is a negative (?)
* else as a UInt (in this case it is none of the above, which makes it a nonnegative whole number)

2022-07-02 13:41 UTC, jeapostrophe commented
Right on, I think we can basically support anything.

2022-08-15 16:56 UTC, DanBurton commented
superceded by https://github.com/reach-sh/reach-lang/pull/1326

2022-08-15 16:56 UTC, closed without merging