Reverse Learning Optimization & Be Sensitive To The Untouchable Vars
reach-sh/reach-lang pull request #1361
Opened 2022-08-23 19:49 UTC by chrisnevers

Fixes #1183

2022-08-23 19:59 UTC, jeapostrophe requested changes
Can you put as part of the PR an example of the before & after for the optimization relative to the learning thing?

2022-08-23 19:59 UTC, jeapostrophe commented on hs/src/Reach/Optimize.hs
> +      | rhs == result && lhs /= result -> [(dv, false)]
`==` may be too specific and you should use `equiv` instead (because of source location / metadata)

2022-08-23 19:59 UTC, jeapostrophe commented on hs/src/Reach/Optimize.hs
> +    (Just dv, _, DLE_PrimOp {}) | not (S.member dv svs) -> doit dv
Name `not (S.member dv svs)` a function like `allowedToRemove` to make it intuitive

2022-08-23 19:59 UTC, jeapostrophe commented on hs/src/Reach/Optimize.hs
> +-- Given that the result of `a` is `DLArg`, learn new bindings
This is cool

2022-08-23 19:59 UTC, jeapostrophe commented on hs/src/Reach/Optimize.hs
>        -- XXX We could see if c' is something like `DLVar x == DLArg y` and add x -> y to the optimization environment. A general way to do this would be to have something that says "If this variable
I think you did this, so you can remove the comment

2022-08-23 20:35 UTC, chrisnevers commented
There's not much interesting logic in this example program, but this shows it working:
```JavaScript
const v2145 : Bool! = value/2131 > lastConsensusTime/2137;
const v2146 : Bool! = (fullUnlock/2135 ? false : true);
const v2147 : Bool! = (v2145 ? v2146 : false);
if v2147 then {
  // Before
  (from 13, (continue [..., (fullUnlock/2135 : Bool, fullUnlock/2135), ... ]))
  // After
  (from 13, (continue [..., (fullUnlock/2135 : Bool, false), ... ]))
}
else { ... }
```

Since `v2147` is `true`, we know that `v2145` and `v2146` must be `true` because the other branch is `false`. If `v2146` is `true`, then `fullUnlock` must be `false`

2022-08-24 11:24 UTC, jeapostrophe approved these changes

2022-08-24 11:25 UTC, merged