CORE-2290 Add new pattern for stdlib loading
reach-sh/reach-lang pull request #1426
Opened 2022-09-15 21:52 UTC by erer1243

2022-09-15 21:58 UTC, jeapostrophe approved these changes

2022-09-15 23:21 UTC, jeapostrophe commented
This needs to be manually rebased because of the new version

2022-09-16 00:55 UTC, erer1243 commented
rebase had no conflicts; why couldn't github do it?

2022-09-16 01:09 UTC, jeapostrophe requested changes

2022-09-16 01:09 UTC, jeapostrophe commented on docs/src/changelog/index.md
> ++ 2022/09/15: Added `{!js} new Reach(env?)`.
I think because this is a lie? It will actually be in rc.1

2022-09-16 01:09 UTC, jeapostrophe commented on docs/src/changelog/index.md
> ++ 2022/09/15: Added `{!js} new Reach(env?)`.
(I tried to modify this in github and couldn't)

2022-09-16 14:32 UTC, merged

2022-09-16 14:35 UTC, jeapostrophe commented
I didn't merge it because the changelog is a lie