js: getEventSigs
reach-sh/reach-lang pull request #1448
Opened 2022-09-30 18:30 UTC by DanBurton

```
$ REACH_CONNECTOR_MODE=ALGO reach run
{ sigs: [ 'pub(UInt)' ], ALGO: [ 'pub(uint64)' ] }
all assertions passed
```

2022-09-30 18:39 UTC, jeapostrophe requested changes
This needs documentation and changelog entry.

With the addition of https://docs.reach.sh/frontend/#js_toString, I think it is acceptable to say that this function actually just is `cosnt getEventSigs = () => bin._getEvents({ reachStdlib: stdlib })`, because we can then tell people, "Yea, it is a list of all the events and their types" and people can call it themselves.

2022-10-07 17:18 UTC, DanBurton commented
* changed the impl to just boil down to _getEvents
* added docs & changelog
* expanded the example to demo how to get and use the ARC-28 sig from this info

2022-10-07 17:19 UTC, jeapostrophe requested changes

2022-10-07 17:19 UTC, jeapostrophe commented on docs/src/frontend/index.md
> +Returns a mapping from event name to the reach types of the data emitted for that event.
```suggestion
Returns a mapping from event name to the Reach types of the data emitted for that event.
```

2022-10-07 17:19 UTC, jeapostrophe approved these changes

2022-10-07 18:49 UTC, merged