Devx 606
reach-sh/reach-lang pull request #1505
Opened 2022-11-03 16:10 UTC by reekamaharaj

Links to reach-lang repo will open in a new tab, links on the navbar will open in a new tab.

2022-11-03 19:54 UTC, TheChronicMonster requested changes

2022-11-03 19:54 UTC, TheChronicMonster commented on docs/gen/generator.js
> +		hp.target = `_blank`;
This line looks like it's indented further than needed.

2022-11-03 19:54 UTC, TheChronicMonster commented on docs/gen/generator.js
> +      } else if (u.startsWith('https')) {
Add spaces inside the parens to match the styling on line 223.

2022-11-03 23:23 UTC, TheChronicMonster approved these changes

2022-11-04 13:22 UTC, jeapostrophe commented on docs/gen/generator.js
> +	    }
```suggestion
      } else if ( u.startsWith('https') ) {
        hp.target = `_blank`;
      }
```

2022-11-04 13:23 UTC, jeapostrophe approved these changes

2022-11-04 13:23 UTC, jeapostrophe commented on docs/gen/generator.js
> +	    }
No heinous demonic tabs

2022-11-04 13:23 UTC, merged