CORE-171
reach-sh/reach-lang pull request #306
Opened 2021-10-06 20:12 UTC by vinmazzi

2021-10-06 20:18 UTC, jeapostrophe commented on .circleci/make.sh
> +cat "${PRE}" > config.gen.yml
I think you should move this line up to 9 and add `exit 0` so it is more clear that this is just an experiment.

2021-10-06 20:18 UTC, jeapostrophe commented on hs/Dockerfile.haskell-build-artifacts
> +FROM ethereum/solc:0.8.7-alpine  AS solc
I would like all of the `0.8.7`s through this and the other files consolidated into one place that can be sourced by all the various Makefiles/etc (like `/DEPS` or something)

2021-10-06 20:19 UTC, jeapostrophe commented on hs/Dockerfile.haskell-build-artifacts
> +RUN cat sol/stdlib_openzep.sol sol/stdlib_reach.sol > sol/stdlib.sol
Ditto

2021-10-06 20:19 UTC, jeapostrophe commented on js/stdlib/Dockerfile
> +RUN mo ts/version.mo.ts > ts/version.ts
Same complaint about duplicating the `Makefile` content

2021-10-06 20:20 UTC, jeapostrophe commented on js/stdlib/Dockerfile
> +RUN mo ts/version.mo.ts > ts/version.ts
Perhaps the answer is that it should be removed from the Makefiles, I'm not sure

2021-11-04 17:53 UTC, jeapostrophe requested changes

2021-11-04 17:53 UTC, jeapostrophe commented on .circleci/config.pre.yml
> +            only: /[0-9]*\.[0-9]*\.[0-9]*/
We always want to do this

2021-11-04 17:53 UTC, jeapostrophe commented on .circleci/config.pre.yml
> +            only: /[0-9]*\.[0-9]*\.[0-9]*/
And this

2021-11-04 17:53 UTC, jeapostrophe commented on .circleci/config.pre.yml
> +  "install-mo":
This isn't used any more

2021-11-04 17:53 UTC, jeapostrophe commented on .circleci/config.yml
> +              only: /[0-9]*\.[0-9]*\.[0-9]*/
We always want to do this

2021-11-04 17:53 UTC, jeapostrophe commented on .circleci/make.sh
> +            only: /[0-9]*\.[0-9]*\.[0-9]*/
We always want this

2021-11-04 17:53 UTC, jeapostrophe commented on .circleci/make.sh
> +    - "hold":
My intention was that you would put this directly into `config.pre.yml`  and it would just require `"build-sink"`

2021-11-04 17:53 UTC, jeapostrophe commented on .circleci/make.sh
> +            only: /[0-9]*\.[0-9]*\.[0-9]*/
We always want this

2021-11-04 17:53 UTC, jeapostrophe commented on .circleci/make.sh
> +            only: /[0-9]*\.[0-9]*\.[0-9]*/
And this

2021-11-04 17:53 UTC, jeapostrophe commented on hs/Makefile
> +build: build-haskell build-reach-cli build-reachc
Duplicate target

2021-11-04 17:53 UTC, jeapostrophe commented on js/stdlib/Dockerfile
> +FROM ethereum/solc:${SOLC_IMAGE} as solc
These are unused

2021-11-04 17:53 UTC, jeapostrophe commented on js/stdlib/Dockerfile
> +ARG SOLC_IMAGE
Unused

2021-11-04 17:53 UTC, jeapostrophe commented on js/stdlib/Makefile
> +	  --build-arg SOLC_IMAGE=${SOLC_IMAGE} \
Unused

2021-11-04 17:53 UTC, jeapostrophe commented on js/stdlib/Makefile
> +	$(ROOT)/scripts/docker-push.sh $(IMAGE)
Duplicate target

2021-11-05 11:05 UTC, vinmazzi commented
Unfortunately we do need the filter tags on all jobs otherwise it never gets executed when the build is off of a tag:

<img width="1190" alt="Screen Shot 2021-11-05 at 7 44 58 AM" src="https://user-images.githubusercontent.com/8799720/140501159-52e4e7ba-c1ee-41e5-81d1-d28b6c952c23.png">

2021-11-05 13:50 UTC, jeapostrophe requested changes

2021-11-05 13:50 UTC, jeapostrophe commented on .circleci/.gitignore
> +/config.dend.yml
Not needed

2021-11-05 13:51 UTC, jeapostrophe commented
Re: the tag filter thing. I think I must be dumb. Doesn't that mean it *only* runs when it is tagged? It reads to me like "There's a filter. Only run in these conditions: there is a tag". Does it not work like that?

2021-12-02 17:57 UTC, jeapostrophe commented
This has moved to a different PR

2021-12-02 17:57 UTC, closed without merging