rename directory for brevity; devs can see README
reach-sh/reach-lang pull request #360
Opened 2021-11-08 20:48 UTC by hamirmahal

This change just renames the directory of the files that the compiler will eventually output from `compiler_outputted_files/` to `data/`.

I added a `README.md` to this directory previously, anyway, so anyone curious what the purpose of this directory is can just read that.

2021-11-08 20:58 UTC, jeapostrophe requested changes
The use of the file in the code would need to change too

2021-11-08 22:58 UTC, hamirmahal commented
Ah! Thank you. I forgot about that.

2eab2e50ca08875a482047321d1177b8e651f5ff should address that.

2021-11-08 23:00 UTC, hamirmahal commented
Ah! Thank you. I forgot about that.

2eab2e50ca08875a482047321d1177b8e651f5ff should address that.

2021-11-09 14:45 UTC, jeapostrophe approved these changes

2021-11-09 14:45 UTC, merged