Updates for new version of RPS
reach-sh/reach-lang pull request #402
Opened 2021-11-21 16:11 UTC by TheChronicMonster

New folder structure and updated markdown for Rock, Paper, Scissors

## Summary

I've copied the current /tut-n/ directory structure with mirrored /rps-n-lorem/ directories in /examples/.
This new structure will allow for more expansive getting started docs without disturbing the scrbl documentation that is currently in use. 

The new RPS index.md tutorial is 90% complete. 
I need to update URLs for the snippets, double check grammar/typos, and add a few subheadings. However, all Primary content and structure is in place.

2021-11-22 16:59 UTC, jeapostrophe requested changes
I think rather than making new `examples/rps-X-Y` directories, we should rename the old ones and update the emeritus site too. (A simple `git mv`. If you want, I can do that and you change just commit the `docs` changes)

2021-11-23 06:51 UTC, TheChronicMonster commented
Updated tut-n directories and references to matching rps-n-lorem structure.

Calls to tut-n related files were pervasive throughout the system. References to tut-n files have been replaced so links remain intact. 

Built repo in /docs/ locally and tested current and new developer portals. Code snippets load properly, links work as expected. However, links to source code in GH currently leads to 404, but I believe this will resolve itself once the files and directories are updated.

2021-11-23 21:06 UTC, jeapostrophe requested changes

2021-11-23 21:06 UTC, jeapostrophe commented on docs/dev/rewire.sh
> +r overview rps/overview
This should still be `tut`

2021-11-23 21:06 UTC, jeapostrophe commented on docs/dev/rewire.sh
> +r rps-7-rpc rps/rps/7-rpc
These too

2021-11-23 21:06 UTC, jeapostrophe commented on docs/scrbl/guide-limits.scrbl
> +Today, Reach is a powerful language for building decentralized applications, as demonstrated in @seclink["overview"]{the overview}, @seclink["rps"]{the tutorial}, and the @seclink["workshop"]{worksho
You can't rename the sections, because that will break the old links.

2021-11-23 21:06 UTC, jeapostrophe commented on docs/scrbl/guide-rpc.scrbl
> +The @seclink["rps-7-rpc"]{tutorial section on RPC-based frontends} provides a walkthrough of using these libraries.
Ditto

2021-11-23 21:06 UTC, jeapostrophe commented on examples/tut-7-array/index.mjs
> -import { loadStdlib } from '@reach-sh/stdlib';
You should not have deleted this directory

2021-11-24 01:03 UTC, closed without merging