add min balance func
reach-sh/reach-lang pull request #519
Opened 2022-01-20 12:37 UTC by temptemp3

## Summary

In ALGO, a portion of accounts is made not available based on account usage of apps and storage on the network. The `stdlib.minBalance(acc)` function computes amount that an account may use in a future transaction.

Min balance calculations use the following as a reference:
https://github.com/reach-sh/reach-lang.git

Function is accompanied by an `minBalance` in `examples`.

Yes, I believe it should be added to the change long and docs as a ALGO specific feature.

2022-01-20 16:19 UTC, jeapostrophe requested changes
If you don't want to make these changes, just say so and I will

2022-01-20 16:19 UTC, jeapostrophe commented on js/stdlib/ts/ALGO.ts
> -  'apps-local-state'?: Array<AppState>
Ditto

2022-01-20 16:19 UTC, jeapostrophe commented on js/stdlib/ts/ALGO.ts
> +  'created-apps': Array<AppInfo>
These are all `?`

2022-01-20 16:19 UTC, jeapostrophe commented on js/stdlib/ts/ALGO.ts
> +  let createdApps = ai['created-apps']
You should use `const` because you don't mutate them

2022-01-20 16:19 UTC, jeapostrophe commented on js/stdlib/ts/ALGO.ts
> +
We don't want extra spaces

2022-01-21 12:42 UTC, temptemp3 commented on js/stdlib/ts/ALGO.ts
> -  'assets'?: Array<AccountAssetInfo>,
You're right. I'll fix these.

2022-01-21 13:46 UTC, temptemp3 commented
@jeapostrophe Made some changes. Hope it works. Thx!

2022-01-23 23:08 UTC, AwolDes commented
Excited for this, great work @temptemp3

2022-01-26 18:48 UTC, jeapostrophe commented
I went to merge this today, but because you are doing merges rather than rebasing, I can't. Can you either rebase or squash and update the PR? If you don't want to do either, just tell me and I'll manually make the same changes.

2022-01-27 11:41 UTC, temptemp3 commented
@jeapostrophe let's not try to merge this just yet. Fixing an issue discovered earlier today. About the merges, you're right. I'll try to stay away from resolve conflicts in github!

2022-01-27 13:38 UTC, temptemp3 commented
@jeapostrophe it took some time but I think I got it ; )

2022-01-27 17:26 UTC, jeapostrophe commented
Merged, thanks!

2022-01-27 17:26 UTC, closed without merging