algo client side rate limiting
reach-sh/reach-lang pull request #525
Opened 2022-01-21 17:33 UTC by DanBurton

2022-01-22 16:44 UTC, jeapostrophe commented on js/stdlib/ts/ALGO.ts
> +var currentReqNum: number | undefined = undefined;
`let` not `var`. Var is weird

2022-01-22 16:44 UTC, jeapostrophe commented on js/stdlib/ts/ALGO_ReachHTTPClient.ts
> +}
This code is asking for abstraction of `this.bc["delete"]` etc

2022-01-22 16:44 UTC, jeapostrophe commented on js/stdlib/ts/ALGO_UTBC.ts
> +// XXX get them to export this. Webpack can't pluck the source file so we copy/paste it instead.
Please make an issue or PR to `js-algorand-sdk`

2022-01-26 18:01 UTC, jeapostrophe requested changes

2022-01-26 18:01 UTC, jeapostrophe commented on js/stdlib/ts/ETH_like.ts
> +  console.warn(`setMinMillisBetweenRequests is not yet implemented on this connector`);
I think it should "not supported"

2022-01-26 18:01 UTC, jeapostrophe commented on js/stdlib/ts/ALGO_ReachHTTPClient.ts
> +    return await this._doTheThing(eventDetails, async () => await this.bc.get(relativePath, query, requestHeaders));
Even this could be abstracted with `...(data ? [data] : [])` and then you got one function for 'em all

2022-01-27 18:40 UTC, jeapostrophe requested changes
I realized that adding it to ETH_like doesn't actually add it to ETH and CFX, because there's more to do there. You should add these functions to interfaces.ts and see the error.

Also, docs

2022-01-27 18:52 UTC, DanBurton commented
The changes to interfaces.ts, ETH.ts, and CFX.ts are already in the PR. Working on docs now.

2022-01-27 18:54 UTC, jeapostrophe commented
Ah, I was looking at the changes, not the full thing. Sorry!

2022-01-27 19:45 UTC, jeapostrophe approved these changes

2022-01-27 19:46 UTC, merged