wip exception based implementation of core-579
reach-sh/reach-lang pull request #584
Opened 2022-02-15 16:05 UTC by erer1243

WIP implementation of core-579, still with caveman prints and debugging code. Uploaded for comment on style.

An example that shows the json object that would be uploaded vs what would be printed to the user (everything immediately after the json) 
![image](https://user-images.githubusercontent.com/1377477/154100230-49d3b105-2c3c-4603-978b-64f1f568707a.png)

2022-02-17 14:43 UTC, jeapostrophe requested changes

2022-02-17 14:43 UTC, jeapostrophe commented on examples/donation-balancesOf/index.rsh
> +  declassify(); // make an error
You should test by running on one of the files in `hs/t/n`

2022-02-17 14:43 UTC, jeapostrophe commented on hs/src/Reach/Report.hs
> +reportResult (Right ()) = "Right ()"
I like `\case`

2022-02-17 14:43 UTC, jeapostrophe commented on hs/src/Reach/Report.hs
> +  { cee_json :: String
How about making this a `CompilationError` or a JSON `Value` and then you can put the encoding stuff somewhere else

2022-02-17 14:43 UTC, jeapostrophe commented on hs/src/Reach/Report.hs
> +  show = cee_pretty
This is actually wrong and we do need that unsafe thing, because it exists because the IDE wants to see errors as JSON.

2022-02-17 14:43 UTC, jeapostrophe commented on hs/src/Reach/Report.hs
> +data CompileErrorException = CompileErrorException
I think this type should be somewhere else, perhaps where `CompilationError` is defined.

2022-02-21 03:07 UTC, erer1243 commented
An example using a test from `hs/t/n/` 
![image](https://user-images.githubusercontent.com/1377477/154882614-3c57e2fe-9d9f-44dd-bbbf-3989de41b261.png)

2022-02-21 15:57 UTC, jeapostrophe requested changes
I believe this implementation is ready to merge (once you remove the testing stuff you added)

2022-02-21 19:17 UTC, jeapostrophe commented
Make sure you rebase, because William touched something close

2022-02-22 00:32 UTC, erer1243 commented
Rebased & removed testing stuff. Good to go.

2022-02-22 00:43 UTC, erer1243 commented
Actually, maybe I did something wrong with the rebase. Or misunderstand rebasing in general :P . Looks like what William did still caused a conflict, so I used the web interface to fix it and make that merge commit. We both changed how `CompilationError`s are converted to Strings. I just kept my changes to the relevant part of the file.

2022-02-22 00:51 UTC, jeapostrophe commented
You'll need to remove the merge commit so we can rebase this onto master. Also you should make sure his new code (that prints warnings) also uses your new function.

2022-02-22 00:52 UTC, jeapostrophe commented
When you remove the merge, you'll need to checkout to before it, reset the branch, rebase yourself, then force push. You may want to interactively rebase and squash the commits into one

2022-02-22 01:13 UTC, erer1243 commented
Whoops my local master was not up to date. Wondered why the rebase was so easy the first time. Let's try this one?

2022-02-22 15:55 UTC, jeapostrophe approved these changes

2022-02-22 15:55 UTC, merged