CORE-925 dominant assurance example contract
reach-sh/reach-lang pull request #741
Opened 2022-03-30 17:02 UTC by erer1243

Dominant assurance contract (based on the wikipedia definition :^) ).

I wasn't sure if it was better to have trustworthy maps and the invariant `investors.Map.size() == numInvestors` or untrustworthy maps and no invariant. I left it as the latter because I was flustered by all of the warning messages when it was run haha.

2022-03-30 17:30 UTC, jeapostrophe requested changes
This is cool, huh? Do you want to write a little tutorial about it where you walk through the code and the idea?

2022-03-30 17:30 UTC, jeapostrophe commented on examples/dominant-assurance/index.rsh
> +  E.pay(starterInvestment);
I would put this as part of the original publish on line 45

2022-03-30 17:30 UTC, jeapostrophe commented on examples/dominant-assurance/index.rsh
> +  const investmentTimeout = relativeTime(investmentDuration);
Put a comment that in the real world this would probably be absolute, but we use relative for testing

2022-03-30 17:30 UTC, jeapostrophe commented on examples/dominant-assurance/index.rsh
> +      // && investors.Map.size() == numInvestors
You should do that

2022-03-30 17:30 UTC, jeapostrophe commented on examples/dominant-assurance/index.rsh
> +  setOptions({ untrustworthyMaps: true });
You should not do this... yea the warnings are annoying

2022-03-30 17:30 UTC, jeapostrophe commented on examples/dominant-assurance/index.rsh
> +      Anybody.publish();
For a real program, this should really be an API call because we can't expect a participant to be attached the whole time

2022-03-30 17:30 UTC, jeapostrophe commented on examples/dominant-assurance/index.rsh
> +  E.pay(starterInvestment);
Or at least another API call if you want to separate the entrepreneur from the structure-creator

2022-03-30 17:30 UTC, jeapostrophe commented on examples/dominant-assurance/index.rsh
> +    const failPayTimeout = relativeTime(failPayDuration);
Ditto

2022-03-30 17:30 UTC, jeapostrophe commented on examples/dominant-assurance/index.rsh
> +        Anybody.publish();
Ditto

2022-03-31 16:17 UTC, erer1243 commented
Sure, I'll make a little write-up about this example. That sounds fun

2022-04-03 14:35 UTC, jeapostrophe requested changes

2022-04-03 14:35 UTC, jeapostrophe commented on examples/dominant-assurance/index.rsh
>      transfer(returnedToEntrepreneur).to(E);
You should have some events in this program, probably one here so you can have the investors synchronize on it

2022-04-04 19:55 UTC, jeapostrophe reviewed
Cool!

2022-04-04 20:48 UTC, erer1243 commented
Seems I cannot win with the CI.

2022-04-07 15:16 UTC, jeapostrophe approved these changes

2022-04-07 15:50 UTC, merged