CORE-663 daily devnet ping
reach-sh/reach-lang pull request #749
Opened 2022-03-31 22:36 UTC by erer1243

wip
todo: infer reach version (how?), infer reach userId (should this be the result of whoami at container build time?) 

because docker refuses to accept any files outside of the build context, 3 copies of the script are seemingly needed (or, that's the simplest way)

2022-04-01 14:17 UTC, jeapostrophe requested changes
You should NOT make 3 copies. You should make one script and put as part of the `Makefile`, copying it and (potentially customizing it).

You should look at how `reach` exposes the id and how `reachc` gets (potentially asking @mattaudesse ) and get it the same way. Similarly, the version should be available through an environment variable too

2022-04-01 14:17 UTC, jeapostrophe commented on scripts/devnet-algo/daily-ping.sh
> +    \"userId\": \"ALGO-devnet\",
If this is the userId, then it will be useless

2022-04-06 17:29 UTC, jeapostrophe reviewed
These appears ready for now and I think we should just do it and if Matt thinks there's a better way to do it integrated into the HS, he should make a new Jira task for that

2022-04-06 18:00 UTC, mattaudesse approved these changes
👍🏼

2022-04-08 16:49 UTC, jeapostrophe approved these changes

2022-04-08 16:49 UTC, merged