Initial commit for blackjack v1.
reach-sh/reach-lang pull request #788
Opened 2022-04-11 19:57 UTC by quinnvaughn

## Summary
PR to show how to build a decentralized blackjack game. Version 1 that JP asked me to create.

2022-04-11 20:03 UTC, TheChronicMonster commented on examples/blackjack/README.md
> +This projects shows how to have a decentralized version of blackjack on the blockchain.
This project

2022-04-11 20:06 UTC, jeapostrophe requested changes

2022-04-11 20:06 UTC, jeapostrophe commented on examples/blackjack/index.rsh
> +  suit: CardSuit,
You never look at the suit... it doesn't matter

2022-04-11 20:06 UTC, jeapostrophe commented on examples/blackjack/index.rsh
> +const Card = Object({
So, card should just be the value

2022-04-11 20:06 UTC, jeapostrophe commented on examples/blackjack/index.rsh
> +        when: declassify(interact.keepGoing(handValA)),
I don't think that this program should have `keepGoing` and instead the user should be forced to say "I don't want anything" or "I do want something"

2022-04-11 20:06 UTC, jeapostrophe commented on examples/blackjack/index.rsh
> +    .timeout(relativeTime(DEADLINE), () => {
And then this won't be needed

2022-07-30 14:59 UTC, jeapostrophe commented
Closing this because it is such a bigger problem than this.

2022-07-30 14:59 UTC, closed without merging