DCT-296
reach-sh/reach-lang pull request #819
Opened 2022-04-18 21:54 UTC by Craig-Elre

Add docs-wisdom-2 and docs-wisdom-3 to the repo.

## Summary

2022-04-18 23:50 UTC, TheChronicMonster requested changes
CI failed on the `examples sink`
I believe it's because of the `/` at the end of `docs-wisdom-3/`

2022-04-19 01:39 UTC, jeapostrophe commented
The failure was because of me, something I'm about to fix

2022-04-19 01:59 UTC, jeapostrophe reviewed
Is there supposed to be changes made to the files?

2022-04-19 02:10 UTC, TheChronicMonster commented
I think his only changes were to add the two new directories.

From Craig Re the PR:
"I added two new folders to the repo for WFS to see how Jay responds to
this creation method."

On Mon, Apr 18, 2022 at 8:59 PM Jay McCarthy ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
>
> Is there supposed to be changes made to the files?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/reach-sh/reach-lang/pull/819#pullrequestreview-944976629>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACINWGEE2CZTSDDBE3DXESLVFYHPRANCNFSM5TW6VDWQ>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-04-19 13:11 UTC, Craig-Elre commented
> Is there supposed to be changes made to the files?

There are changes in these files. The two commits with "Update" in front is when I changed the `index.mjs` file to match the changes made in the tutorial.

2022-04-22 13:53 UTC, jeapostrophe approved these changes

2022-04-22 13:53 UTC, jeapostrophe commented on examples/docs-wisdom-2/index.mjs
> +}
Something you need to think about and do with these programs is that the CI won't actual do any tests if you build it this way. You should do something like `rps-8-interact` does to script the two different versions to interact and run automatic tests. @DanBurton Please create a Jira card for this for Oliver to help Craig with on the CORE board.

2022-04-22 13:53 UTC, merged