DCT-309
reach-sh/reach-lang pull request #827
Opened 2022-04-19 17:36 UTC by EBEREGIT

Error Message 98

Replaced `ParticipantClass` with `API`

2022-04-19 18:11 UTC, TheChronicMonster submitted a review, later dismissed

2022-04-22 13:55 UTC, jeapostrophe requested changes

2022-04-22 13:55 UTC, jeapostrophe commented on docs/src/rsh/errors/index.md
> +`{!rsh} API`, and `{!rsh} View` will be exported by the Reach backend.
This should be in addition to, not a replacement.

2022-04-22 18:22 UTC, TheChronicMonster approved these changes
Looks good. Please request a review by Jay.

2022-04-23 13:17 UTC, jeapostrophe commented on docs/src/rsh/errors/index.md
> +Reach backend already produces. For example, the names provided in `{!rsh} Participant`, `{!rsh} ParticipantClass`, `{!rsh} API`, and `{!rsh} View` will be exported by the Reach backend.
This is fine, but also this is an example where the newlines should match the semantics.

2022-04-23 13:18 UTC, merged