DCT-304
reach-sh/reach-lang pull request #834
Opened 2022-04-20 16:21 UTC by EBEREGIT

Error Message 80

Added a note mentioning that it is preferable to use `API` rather than `ParticipantClass` since `ParticipantClass` is being deprecated

2022-04-20 17:49 UTC, TheChronicMonster commented on docs/src/rsh/errors/index.md
>  `{!rsh} ParticipantClass` will attempt to race.
Add `API` to statement:
`{!rsh} ParticipantClass` or `{!rsh} API` will attempt to race.

2022-04-20 17:49 UTC, TheChronicMonster commented on docs/src/rsh/errors/index.md
> +Since `ParticipantClass` is being deprecated, it will be preferable to use `API` in place of `ParticipantClass`.
verb tense:
... it is preferable to use `API`.
drop:
 ~in place of `ParticipantClass`~

2022-04-21 18:14 UTC, TheChronicMonster approved these changes

2022-04-21 18:49 UTC, TheChronicMonster requested changes

2022-04-22 14:34 UTC, jeapostrophe approved these changes

2022-04-22 14:34 UTC, merged