DCT-210
reach-sh/reach-lang pull request #838
Opened 2022-04-21 16:31 UTC by EBEREGIT

`exit` statement

Added an example

2022-04-21 18:41 UTC, TheChronicMonster approved these changes

2022-04-21 19:17 UTC, TheChronicMonster requested changes

2022-04-21 19:17 UTC, TheChronicMonster commented on docs/src/rsh/errors/index.md
> +Since `ParticipantClass` is being deprecated, it is preferable to use `API`.
`ParticipantClass` and `API` need `{!rsh}` prefix.

2022-04-22 14:19 UTC, jeapostrophe commented
Request review from me after JP

2022-04-22 18:00 UTC, closed without merging