DCT-317
reach-sh/reach-lang pull request #839
Opened 2022-04-21 17:27 UTC by EBEREGIT

Error Message 119

Added Code Sample

2022-04-21 18:26 UTC, TheChronicMonster requested changes

2022-04-21 18:26 UTC, TheChronicMonster commented on docs/src/rsh/errors/index.md
> -Since `ParticipantClass` is being deprecated, it will be preferable to use `API` in place of `ParticipantClass`.
The monospaced copy should be `{!rsh} ParticipantClass` and `{!rsh} API`

2022-04-21 18:31 UTC, TheChronicMonster requested changes

2022-04-21 18:31 UTC, TheChronicMonster commented on docs/src/rsh/errors/index.md
> +
This entry is incomplete. 
We need to explicitly state that this sample is erroneous and then create a sample that is correct and explicitly state that the example is the proper way to use `didPublish()`

2022-04-21 18:31 UTC, TheChronicMonster commented on docs/src/rsh/errors/index.md
> +  didPublish(handAlice)
Missing a semicolon.

2022-04-22 14:13 UTC, jeapostrophe commented
Please request a review from me once @TheChronicMonster approves

2022-04-22 15:13 UTC, jeapostrophe commented
This commit can no longer be merged because you did a merge rather than a rebase

2022-04-22 15:19 UTC, closed without merging