Call home deps missing
reach-sh/reach-lang pull request #876
Opened 2022-04-29 13:23 UTC by vinmazzi

## Summary
This PR is based off of the install_docker branch.

This code introduces the creation of the REACHC_ID and the compileLog call when some of the dependencies are not installed.

2022-04-29 13:34 UTC, jeapostrophe commented on reach
> +  CALL_HOME_ENDPOINT="https://y9fr4e7fyl.execute-api.us-east-2.amazonaws.com/live/submit"
Is that really the URL? What's wrong with https://github.com/reach-sh/reach-lang/blob/master/hs/src/Reach/Report.hs#L34

2022-05-03 13:08 UTC, jeapostrophe requested changes

2022-05-03 13:08 UTC, jeapostrophe commented on reach
> +  -e 's/{{REACH_VERSION}}/0.1234/g' \
I think this version should be different; like 0.0.0 or something like that

2022-05-11 17:25 UTC, jeapostrophe requested changes
I'd like @mattaudesse to do final approval

2022-05-11 17:25 UTC, jeapostrophe commented on reach
> +  START_TIME=$1
You take it as an argument

2022-05-11 17:25 UTC, jeapostrophe commented on reach
> +  START_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
But then replace it

Also, I believe that we've switched to only using the date, not the time too

2022-05-11 17:25 UTC, jeapostrophe commented on reach
> +
Blasphemous newline

2022-05-11 17:51 UTC, mattaudesse requested changes

2022-05-18 18:41 UTC, closed without merging