DCT-237
reach-sh/reach-lang pull request #966
Opened 2022-05-12 08:07 UTC by EBEREGIT

### `Either`

Added code sample

2022-05-12 14:29 UTC, jeapostrophe requested changes

2022-05-12 14:29 UTC, jeapostrophe commented on docs/src/rsh/compute/index.md
> +See following example summarizes all that have been said above:
grammar

2022-05-13 14:51 UTC, jeapostrophe commented on docs/src/rsh/compute/index.md
> +See following example summarizes all that have been said above:
Don't just delete the offending line, improve it @TheChronicMonster

2022-05-14 02:56 UTC, TheChronicMonster requested changes

2022-05-14 02:56 UTC, TheChronicMonster commented on docs/src/rsh/compute/index.md
> -See following example summarizes all that have been said above:
@EBEREGIT, we discussed this line in our morning standup. Please make the revisions per our conversation.

2022-05-16 17:38 UTC, TheChronicMonster approved these changes

2022-05-16 17:58 UTC, jeapostrophe approved these changes

2022-05-16 17:58 UTC, merged