DCT-239
reach-sh/reach-lang pull request #968
Opened 2022-05-13 07:47 UTC by EBEREGIT

### `makeEnum`

Added code sample

2022-05-13 18:30 UTC, TheChronicMonster requested changes

2022-05-13 18:30 UTC, TheChronicMonster commented on docs/src/rsh/compute/index.md
> +load: ./examples/secured-loan/index.rsh
`load` URL should not be prefixed with a '.', only prefix with '/'.

2022-05-13 18:32 UTC, TheChronicMonster requested changes

2022-05-13 18:32 UTC, TheChronicMonster commented on docs/src/rsh/compute/index.md
> +load: ./examples/secured-loan/index.rsh
`load` URL should only be prefixed with a '/' forward slash. '.' breaks the link in docs portal.

2022-05-16 17:33 UTC, TheChronicMonster submitted a review, later dismissed

2022-05-16 17:58 UTC, jeapostrophe commented
Conflicts, also my taste is to have some introductory comment about the blurb

2022-05-17 07:28 UTC, closed without merging