DCT 247
reach-sh/reach-lang pull request #988
Opened 2022-05-16 09:17 UTC by EBEREGIT

### `lastConsensusTime `

Added code sample

2022-05-16 12:27 UTC, TheChronicMonster requested changes

2022-05-16 12:27 UTC, TheChronicMonster commented on docs/src/rsh/compute/index.md
> +range: 17 - 17
This example does not add new information as compared to the syntactical reference of `lastConsensusTime`. Samples should provide an example of how the code may be used in a real DApp. 
The idea is that a Reach developer can copy and paste our sample and then modify per the needs of their program. 
In this example, we should show lines 12 - 18.

2022-05-16 17:24 UTC, TheChronicMonster submitted a review, later dismissed

2022-05-16 17:59 UTC, jeapostrophe commented
I like some introductory comment

2022-05-17 15:11 UTC, TheChronicMonster commented on docs/src/rsh/compute/index.md
> +Notice how `{!rsh} lastConsensusTime` is called on line 17 after the publication on line 12.
Please see [PR #993](https://github.com/reach-sh/reach-lang/pull/993/files/4ed2cf7c3f9dac6d9b75136f5bb62bb0b36285da)

For an example of an intuitive explanation of the sample. 

If you want to talk about the code samples please schedule a call with me.

2022-05-18 22:12 UTC, jeapostrophe approved these changes

2022-05-18 22:13 UTC, jeapostrophe commented
This needs to be rebased manually I think

2022-05-19 06:31 UTC, closed without merging