DCT-248
reach-sh/reach-lang pull request #989
Opened 2022-05-16 09:24 UTC by EBEREGIT

### `lastConsensusSecs`

Added code sample

2022-05-16 12:29 UTC, TheChronicMonster requested changes

2022-05-16 12:29 UTC, TheChronicMonster commented on docs/src/rsh/compute/index.md
> +range: 18 - 18
Same thing here. Samples should provide more context than the syntax reference. 

Let's find a different example so we're not showing a duplicate sample right after the other.

2022-05-16 17:29 UTC, TheChronicMonster approved these changes

2022-05-16 17:59 UTC, jeapostrophe commented
Re: transition statement

2022-05-16 19:50 UTC, TheChronicMonster commented
> 

@jeapostrophe we want to avoid a string of "In the example below" statements in the documentation. 
However, perhaps we can structure the entries as:
syntax reference
precise explanation
sample
intuitive explanation referencing sample

What do you think?

2022-05-16 20:19 UTC, jeapostrophe commented
That's good for me.

2022-05-16 22:20 UTC, TheChronicMonster commented
> > 
> 
> @jeapostrophe we want to avoid a string of "In the example below" statements in the documentation. However, perhaps we can structure the entries as: syntax reference precise explanation sample intuitive explanation referencing sample
> 
> What do you think?

@EBEREGIT Please update this, and the other PRs with explanations of the samples.

2022-05-17 22:38 UTC, jeapostrophe approved these changes

2022-05-17 22:38 UTC, merged