DCT-287
reach-sh/reach-lang pull request #992
Opened 2022-05-16 18:12 UTC by Craig-Elre

Add the Wisdom For Sale tutorial and all files required for it.
Also, update the tutorial page to add WFS to it.

I did include some images that I decided not to use (reach-run-1 through reach-run-3), but could be used if it is decided that a further description of this process would be useful.

2022-05-18 18:39 UTC, TheChronicMonster requested changes

2022-05-18 18:39 UTC, TheChronicMonster commented on docs/src/tut/wfs/index.md
> +`index.mjs` and `index.rsh` are the default frontend and backend filenames respectively. The Reach compiler compiles index.rsh into index.main.mjs.
Backtick file names.

2022-05-18 18:39 UTC, TheChronicMonster commented on docs/src/tut/wfs/index.md
> +# {#wfs-16} Attach to the contract (buyer)
This is a good section to add an intuitive explanation about interactive command-lines and how we accomplish that with the `ask` object.

2022-05-18 18:39 UTC, TheChronicMonster commented on docs/src/tut/wfs/index.md
> +## {#wfs-2} Reach Mode Diagram
As part of the second draft, be observant of places that intuitive explanations can be inserted. Identify the topics you're teaching directly and indirectly and use those introductory moments as a way to enhance the value of the tutorial for the student. 

IMO, this guide teaches the modes of Reach
The standard library
devnet vs testnet vs mainnet
standard and atomic units
connection modes and networks
How Reach uses Docker
Attaching to a contract
payments and transfers

2022-05-18 18:39 UTC, TheChronicMonster commented on docs/src/tut/wfs/index.md
> +    * Line 1: The buyer always pays the contract.
Line numbers don't match the code

2022-05-18 20:59 UTC, Craig-Elre commented on docs/src/tut/wfs/index.md
> +1. Replace your two `console.log` additions with the following, and run again:
That occurs in the `index.mjs` file of `docs-wisdom-4`, in `docs-wisdom-3`, I use 
`console.log(``The standard unit is ${stdlib.standardUnit}``);
console.log(``The atomic unit is ${stdlib.atomicUnit}``);`

I had to add the extra backticks above to get the code to show up as code, each one is a single backtick

2022-06-10 13:17 UTC, TheChronicMonster commented
@Craig-Elre Several conflicting files need to be resolved; would not `make`

2022-06-13 15:05 UTC, closed without merging