DCT-256
reach-sh/reach-lang pull request #997
Opened 2022-05-17 10:05 UTC by EBEREGIT

### `implies`

Added code sample

2022-05-18 22:07 UTC, jeapostrophe requested changes

2022-05-18 22:07 UTC, jeapostrophe commented on docs/src/rsh/compute/index.md
> +or `isNone(randomsM[this])` evaluates to `{!rsh} true`.
`!rsh` and no newline

2022-05-20 18:14 UTC, jeapostrophe requested changes

2022-05-20 18:14 UTC, jeapostrophe commented on docs/src/rsh/compute/index.md
> +On line 54, `{!rsh} implies` would return `{!rsh} true` if `{!rsh} when` is `{!rsh} false` or `isNone(randomsM[this])` evaluates to `{!rsh} true`.
`{!rsh}`

2022-05-25 19:46 UTC, TheChronicMonster approved these changes
Looks good. Waiting on [DCT-429](https://github.com/reach-sh/reach-lang/pull/1028/files#) to close before `rebase and merge`.

2022-05-27 16:55 UTC, merged